- hosts: galera_servers
  gather_facts: true
  become: true
  roles:
    - role: liviuchircu.ansible_role_xtradb_cluster
      xtradb_cluster_name: "prod-customer"
      xtradb_sst_user: sstuser
      xtradb_sst_password: s3cr3t
      xtradb_root_password: yolo

      xtradb_nodes_group: "galera_servers"
      xtradb_bind_interface: eth0
      xtradb_databases:
        - name: dummydb
      xtradb_users:
        - name: dummydb
          password: passworkd
          priv: 'dummydb.*:GRANT,ALL'
